### ISSUE TITLE
Appending to errors doesn't stop the pipeline

### ISSUE THREAD

**Issue by zacbrannelly** [a2i2/surround#145]
Appending to `surround_data.errors` during any stage in the pipeline no longer stops the pipeline.

**Comment by zacbrannelly** [comment]
Currently only exceptions will stop the pipeline. 
Errors will need their own data structure. So the reason of errors can be seen/inspected.

**Comment by ScottyB** [comment]
The data structure for errors does not need to be implemented in Surround at this stage as we are still discovering what should be in that object. However, the `finaliser` stage of an assembly should still  run.

**Comment by AkshatBajaj** [comment]
> The data structure for errors does not need to be implemented in Surround at this stage as we are still discovering what should be in that object. However, the `finaliser` stage of an assembly should still run.

This works as you mentioned here. Should we close the issue ?

**Comment by AkshatBajaj** [comment]
After careful consideration, I have come to few conclusions:

 - The title of this issue is misleading, it should be named appending to errors doesn't stop the current stage. It does stop the pipeline
 - As @ScottyB  mentioned, the finaliser stage should still run, which is what happens regardless of whether we append to state errors or manually raise an exception

This is the expected behaviour of surround at least for now, so closing this issue @zacbrannelly
