### ISSUE TITLE
Add test case, example not working but test is ok

### ISSUE THREAD

**Issue by DungLai** [a2i2/surround#32]
As in the capture, running `python setup.py test` returns OK but hello world example is not working.
Error: 

> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     from surround import Stage, PipelineData, Pipeline
> ImportError: No module named 'surround'

Reason: missing `python3 setup.py install`

Consider adding new test cases for installation.

![image](https://user-images.githubusercontent.com/27338301/50673941-0d5d2f80-1036-11e9-8d07-7e163fc69b2e.png)

Cheers,
Tuan.

**Comment by AkshatBajaj** [comment]
The reason is `python3 setup.py test` does not need prior installation. As mentioned here: https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

<img width="823" alt="Screen Shot 2019-04-02 at 4 36 52 pm" src="https://user-images.githubusercontent.com/32318980/55378636-8dc3fb80-5565-11e9-9c82-a8fe76c5a600.png">

So, `python3 setup.py test` will never throw an error if module is not present. Run tests manually for that.
`python3 -m unittest <module-name>`
I think we can close this issue. Thoughts @ScottyB
